export const STATE_STORAGE_KEYS = {
  SKILLFORGE_BALANCES_STATE: 'SKILLFORGE_BALANCES_STATE',
  SKILLFORGE_USER_CONFIG_STATE: 'SKILLFORGE_USER_CONFIG_STATE',
  SKILLFORGE_METADATA_STATE: 'SKILLFORGE_METADATA_STATE',
  SKILLFORGE_VERSION_STATE: 'SKILLFORGE_VERSION_STATE'
}
