name: Publish

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - V2-development
      - V2

jobs:
  publish:
    # if: github.event.pull_request.merged == true # Condition
    runs-on: ubuntu-latest
    
    steps:
        - name: "Checkout"
          uses: actions/checkout@v4
          with:
            # we need full depth here for lerna tags
            fetch-depth: 0

        - name: Install dependencies
          run: yarn install --frozen-lockfile

        - name: Build projects
          # skip building apps
          run: yarn build:packages

        - name: "Version and publish"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor}}@users.noreply.github.com"
            npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"

            if [ ${{ github.base_ref }} != V2 ]; then
              git reset --hard origin/${{ github.base_ref }}
              git checkout ${{ github.head_ref }}
              npx lerna@6.6.2 version --conventional-commits --conventional-prerelease --preid alpha --yes --loglevel silly
              npx lerna@6.6.2 publish from-git --no-verify-access --dist-tag alpha --yes --loglevel silly
            else
              git reset --hard origin/V2
              npx lerna@6.6.2 version --conventional-commits --conventional-graduate --yes
              npx lerna@6.6.2 publish from-git --no-verify-access --yes
            fi

